//! Static asset serving with proper HTTP cache headers.
//!
//! The compiled Tailwind stylesheet is embedded into the binary at build time
//! via `include_bytes!`. On first request we compute a SHA-256 ETag; subsequent
//! requests honour `If-None-Match` and return 304 Not Modified when the ETag
//! matches, avoiding any payload transfer.
//!
//! Cache-Control: public, max-age=31536000, immutable
//!   → browsers cache for 1 year; "immutable" tells them not to revalidate.
//!   → The filename in the template can be versioned (app.v2.css) to bust the
//!     cache when content changes — or just deploy and let ETag handle it.

use axum::{
    http::{header, HeaderMap, StatusCode},
    response::{IntoResponse, Response},
};
use once_cell::sync::Lazy;
use sha2::{Digest, Sha256};

// ── Embed the compiled CSS at build time ──────────────────────────────────────
//
// This file is generated by:
//   npx tailwindcss -i src/tailwind.css -o static/css/app.css --minify
//
// The Docker build runs this before `cargo build` (see Dockerfile).
// The resulting ~5 KB file is baked into the binary — no disk I/O at runtime.

static CSS_BYTES: &[u8] = include_bytes!("../static/css/app.css");

/// Pre-computed ETag: `"<hex-sha256>"` (with surrounding quotes as per RFC 7232).
static CSS_ETAG: Lazy<String> = Lazy::new(|| {
    let hash = Sha256::digest(CSS_BYTES);
    format!("\"{}\"", hex::encode(hash))
});

// ── Handler ───────────────────────────────────────────────────────────────────

/// GET /static/css/app.css
///
/// Returns the embedded Tailwind stylesheet with:
///   • `Cache-Control: public, max-age=31536000, immutable`
///   • `ETag: "<sha256>"`
///   • `304 Not Modified` when `If-None-Match` matches the ETag
pub async fn handle_static_css(request_headers: HeaderMap) -> Response {
    // Conditional GET — honour If-None-Match
    if let Some(inm) = request_headers.get(header::IF_NONE_MATCH) {
        if inm.as_bytes() == CSS_ETAG.as_bytes() {
            return StatusCode::NOT_MODIFIED.into_response();
        }
    }

    (
        [
            (header::CONTENT_TYPE,  "text/css; charset=utf-8"),
            (header::CACHE_CONTROL, "public, max-age=31536000, immutable"),
            (header::ETAG,          CSS_ETAG.as_str()),
        ],
        CSS_BYTES,
    )
        .into_response()
}
